/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package play;

import java.awt.Label;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Chaitanya Salunkhe
 */

public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    int count = 0;
    String str = "X";
    public Game(JFrame ref) {
        initComponents();
        setLocationRelativeTo(ref);
        setVisible(true);
    }
    public void compare()
    {
        String t1 = tex1.getText();
        String t2 = tex2.getText();
        String t3 = tex3.getText();
        String t4 = tex4.getText();
        String t5 = tex5.getText();
        String t6 = tex6.getText();
        String t7 = tex7.getText();
        String t8 = tex8.getText();
        String t9 = tex9.getText();
        System.out.println();
        
        if((t1.equals(t2) && t3.equals(t2) && !t2.isEmpty()) || (t1.equals(t4) && t7.equals(t4) && !t4.isEmpty()) || (t1.equals(t5) && t9.equals(t5) && !t5.isEmpty() ))
        {
            if(str.equals("X"))
            {
                Message.mes(this," Player1 Won the Game");
            }
            else
            {
                Message.mes(this," Player2 Won the Game");
            }
            dispose();
        }
        else if((t9.equals(t8) && t7.equals(t8) && !t8.isEmpty()) || (t9.equals(t6) && t3.equals(t6) && !t6.isEmpty()) || (t3.equals(t5) && t7.equals(t5) && !t5.isEmpty()))
        {
            if(str.equals("X"))
            {
                Message.mes(this," Player1 Won the Game");
            }
            else
            {
                Message.mes(this," Player2 Won the Game");
            }
            dispose();
        }
        else if((t2.equals(t5) && t8.equals(t5) && !t5.isEmpty()) || (t4.equals(t5) && t6.equals(t5)&& !t5.isEmpty())) 
        {
            if(str.equals("X"))
            {
                Message.mes(this," Player1 Won the Game");
            }
            else
            {
                Message.mes(this," Player2 Won the Game");
            }
            dispose();
        }
    }
    public void playy(JLabel c)
    {
        String s = c.getText();
        if(count<6 && s.isEmpty())
        {
           c.setText(str);
           compare();
           if(str.equals("X"))
           {
              str = "O";
           }
           else
           {
              str = "X";
           } 
           count++;
        }
        else if(count==6 && s.isEmpty())
        {
            Message.mes(this,"Please click on you item to move");
        }
        else if(count==6 && !s.isEmpty() && s.equals(str))
        {
            c.setText("");
            count--;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tex3 = new javax.swing.JLabel();
        tex1 = new javax.swing.JLabel();
        tex2 = new javax.swing.JLabel();
        tex5 = new javax.swing.JLabel();
        tex4 = new javax.swing.JLabel();
        tex6 = new javax.swing.JLabel();
        tex7 = new javax.swing.JLabel();
        tex9 = new javax.swing.JLabel();
        tex8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tex3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex3MouseClicked(evt);
            }
        });

        tex1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex1MouseClicked(evt);
            }
        });

        tex2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex2MouseClicked(evt);
            }
        });

        tex5.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex5MouseClicked(evt);
            }
        });

        tex4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex4MouseClicked(evt);
            }
        });

        tex6.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex6MouseClicked(evt);
            }
        });

        tex7.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex7MouseClicked(evt);
            }
        });

        tex9.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex9MouseClicked(evt);
            }
        });

        tex8.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        tex8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tex8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tex8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tex8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tex7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tex2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tex3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tex5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tex8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tex9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tex6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tex1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex1MouseClicked
        playy(tex1);
    }//GEN-LAST:event_tex1MouseClicked

    private void tex2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex2MouseClicked
        playy(tex2);
    }//GEN-LAST:event_tex2MouseClicked

    private void tex3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex3MouseClicked
        playy(tex3);
    }//GEN-LAST:event_tex3MouseClicked

    private void tex4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex4MouseClicked
        playy(tex4);
    }//GEN-LAST:event_tex4MouseClicked

    private void tex5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex5MouseClicked
        playy(tex5);
    }//GEN-LAST:event_tex5MouseClicked

    private void tex6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex6MouseClicked
        playy(tex6);
    }//GEN-LAST:event_tex6MouseClicked

    private void tex7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex7MouseClicked
        playy(tex7);
    }//GEN-LAST:event_tex7MouseClicked

    private void tex8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex8MouseClicked
        playy(tex8);
    }//GEN-LAST:event_tex8MouseClicked

    private void tex9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tex9MouseClicked
        playy(tex9);
    }//GEN-LAST:event_tex9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tex1;
    private javax.swing.JLabel tex2;
    private javax.swing.JLabel tex3;
    private javax.swing.JLabel tex4;
    private javax.swing.JLabel tex5;
    private javax.swing.JLabel tex6;
    private javax.swing.JLabel tex7;
    private javax.swing.JLabel tex8;
    private javax.swing.JLabel tex9;
    // End of variables declaration//GEN-END:variables
}
